Project Users {
  database_type: 'PostgreSQL'
  Note: '''
    # Hangman Game Database
    **Database for users service**
  '''
}
Table users {
  id int [pk, increment]
  name varchar
  created_at varchar [note: 'When user created']
  updated_at varchar [note: 'When user updated']
  note: "table 'users' contains user information"
}
Table credentials {
  id int [pk, increment]
  email varchar [not null, unique]
  password_hash varchar
  admin boolean
  active boolean
  user_id int [not null, unique]
  created_at varchar [note: 'When credential created']
  updated_at varchar [note: 'When credential updated']
  note: "table 'credentials' contains user credential"
}
Table email_tokens {
  id int [pk, increment]
  token varchar [not null, unique]
  created_at varchar [note: 'When token created']
  updated_at varchar [note: 'When token updated']
  note: "table 'email_tokens' contains active tokens from email requests"
}
Ref: credentials.user_id > users.id